#!/system/bin/sh
# extract_missing_offsets.sh - 从运行中的设备提取 GhostLock 所需的缺失偏移
#
# 用法:
#   adb push tools/extract_missing_offsets.sh /data/local/tmp/
#   adb shell su -c "sh /data/local/tmp/extract_missing_offsets.sh"
#
# 输出: /data/local/tmp/ghostlock_missing_offsets.h
# 需要 root 权限读取 /proc/kallsyms

OUTPUT="/data/local/tmp/ghostlock_missing_offsets.h"

echo "/* Auto-generated by extract_missing_offsets.sh */" > $OUTPUT
echo "/* Run on aresin (MT6893, 4.14.186) with root */" >> $OUTPUT
echo "" >> $OUTPUT

# Check root
if [ "$(id -u)" != "0" ]; then
    echo "[!] 需要 root 权限运行此脚本"
    echo "    用法: su -c 'sh /data/local/tmp/extract_missing_offsets.sh'"
    exit 1
fi

KBASE="0xffffff939bc80000"

echo "[*] 提取内核符号地址..."

# Helper: get symbol address from kallsyms and compute offset from KIMAGE
get_sym() {
    local name="$1"
    local define="$2"
    local addr=$(grep -w "$name" /proc/kallsyms 2>/dev/null | head -1 | awk '{print $1}')
    if [ -n "$addr" ] && [ "$addr" != "0000000000000000" ]; then
        # Compute offset from KIMAGE_TEXT_BASE
        echo "#define ${define}_OFF 0x$(python3 -c "print(hex(0x$addr - $KBASE)[2:])" 2>/dev/null || echo "TODO")ULL  /* $name = 0x$addr */" >> $OUTPUT
        echo "  $name = 0x$addr"
    else
        echo "#define ${define}_OFF 0x0ULL  /* $name: NOT FOUND - need vmlinux analysis */" >> $OUTPUT
        echo "  $name = [未找到]"
    fi
}

echo "[*] 提取 pipe 相关符号..."
get_sym "generic_pipe_buf_ops" "ANON_PIPE_BUF_OPS"
get_sym "generic_pipe_buf_release" "GENERIC_PIPE_BUF_RELEASE"
get_sym "generic_pipe_buf_confirm" "GENERIC_PIPE_BUF_CONFIRM"

echo "[*] 提取 slab 相关符号..."
get_sym "kmalloc_caches" "KMALLOC_CACHES"

echo "[*] 提取 SELinux 相关符号..."
get_sym "selinux_blob_sizes" "SELINUX_BLOB_SIZES"
get_sym "security_hook_heads" "SECURITY_HOOK_HEADS"

echo "[*] 提取 ashmem 相关符号..."
get_sym "ashmem_misc_fops" "ASHMEM_MISC_FOPS"
get_sym "ashmem_fops" "ASHMEM_FOPS"
get_sym "ashmem_ioctl" "ASHMEM_IOCTL"
get_sym "ashmem_compat_ioctl" "ASHMEM_COMPAT_IOCTL"
get_sym "ashmem_mmap" "ASHMEM_MMAP"
get_sym "ashmem_open" "ASHMEM_OPEN"
get_sym "ashmem_release" "ASHMEM_RELEASE"
get_sym "ashmem_show_fdinfo" "ASHMEM_SHOW_FDINFO"

echo "[*] 提取 configfs 相关符号..."
get_sym "configfs_read_iter" "CONFIGFS_READ_ITER"
get_sym "configfs_bin_write_iter" "CONFIGFS_BIN_WRITE_ITER"

echo "[*] 提取其他符号..."
get_sym "copy_splice_read" "COPY_SPLICE_READ"
get_sym "noop_llseek" "NOOP_LLSEEK"
get_sym "anon_pipe_buf_ops" "ANON_PIPE_BUF_OPS_ALT"

echo "" >> $OUTPUT
echo "/* 提取完成时间: $(date) */" >> $OUTPUT
echo "/* 设备: $(getprop ro.product.device) $(uname -r) */" >> $OUTPUT

echo ""
echo "[+] 输出文件: $OUTPUT"
echo "[+] 请将此文件内容合并到 src/targets/aresin/target.h"
echo ""
cat $OUTPUT
